// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/stores/v1/stores.proto

package stores_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AddressId     string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,4,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStoreRequest) Reset() {
	*x = AddStoreRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStoreRequest) ProtoMessage() {}

func (x *AddStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStoreRequest.ProtoReflect.Descriptor instead.
func (*AddStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{0}
}

func (x *AddStoreRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *AddStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddStoreRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *AddStoreRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type AddStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id            *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStoreResponse) Reset() {
	*x = AddStoreResponse{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStoreResponse) ProtoMessage() {}

func (x *AddStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStoreResponse.ProtoReflect.Descriptor instead.
func (*AddStoreResponse) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{1}
}

func (x *AddStoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddStoreResponse) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type GetStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRequest) Reset() {
	*x = GetStoreRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRequest) ProtoMessage() {}

func (x *GetStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRequest.ProtoReflect.Descriptor instead.
func (*GetStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{2}
}

func (x *GetStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *Store                 `protobuf:"bytes,1,opt,name=store,proto3,oneof" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreResponse) Reset() {
	*x = GetStoreResponse{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreResponse) ProtoMessage() {}

func (x *GetStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreResponse.ProtoReflect.Descriptor instead.
func (*GetStoreResponse) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{3}
}

func (x *GetStoreResponse) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	AddressId     string                 `protobuf:"bytes,4,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{4}
}

func (x *Store) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Store) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

type UpdateStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	AddressId     string                 `protobuf:"bytes,4,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,5,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoreRequest) Reset() {
	*x = UpdateStoreRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoreRequest) ProtoMessage() {}

func (x *UpdateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStoreRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *UpdateStoreRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *UpdateStoreRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type UpdateStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Store         *Store                 `protobuf:"bytes,2,opt,name=store,proto3,oneof" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoreResponse) Reset() {
	*x = UpdateStoreResponse{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoreResponse) ProtoMessage() {}

func (x *UpdateStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateStoreResponse) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpdateStoreResponse) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type DeleteStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,2,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoreRequest) Reset() {
	*x = DeleteStoreRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreRequest) ProtoMessage() {}

func (x *DeleteStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteStoreRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

type DeleteStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoreResponse) Reset() {
	*x = DeleteStoreResponse{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreResponse) ProtoMessage() {}

func (x *DeleteStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteStoreResponse) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteStoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SearchStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AddressId     string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	AddressStr    string                 `protobuf:"bytes,4,opt,name=address_str,json=addressStr,proto3" json:"address_str,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Distance      uint32                 `protobuf:"varint,7,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStoreRequest) Reset() {
	*x = SearchStoreRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStoreRequest) ProtoMessage() {}

func (x *SearchStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStoreRequest.ProtoReflect.Descriptor instead.
func (*SearchStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{9}
}

func (x *SearchStoreRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *SearchStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchStoreRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *SearchStoreRequest) GetAddressStr() string {
	if x != nil {
		return x.AddressStr
	}
	return ""
}

func (x *SearchStoreRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SearchStoreRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SearchStoreRequest) GetDistance() uint32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type SearchStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*StoreGeo            `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	Geo           *Point                 `protobuf:"bytes,2,opt,name=geo,proto3,oneof" json:"geo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStoreResponse) Reset() {
	*x = SearchStoreResponse{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStoreResponse) ProtoMessage() {}

func (x *SearchStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStoreResponse.ProtoReflect.Descriptor instead.
func (*SearchStoreResponse) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{10}
}

func (x *SearchStoreResponse) GetStores() []*StoreGeo {
	if x != nil {
		return x.Stores
	}
	return nil
}

func (x *SearchStoreResponse) GetGeo() *Point {
	if x != nil {
		return x.Geo
	}
	return nil
}

type StoreGeo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *Store                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Distance      *float32               `protobuf:"fixed32,2,opt,name=distance,proto3,oneof" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreGeo) Reset() {
	*x = StoreGeo{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGeo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGeo) ProtoMessage() {}

func (x *StoreGeo) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreGeo.ProtoReflect.Descriptor instead.
func (*StoreGeo) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{11}
}

func (x *StoreGeo) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *StoreGeo) GetDistance() float32 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{12}
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_api_stores_v1_stores_proto protoreflect.FileDescriptor

const file_api_stores_v1_stores_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/stores/v1/stores.proto\x12\tstores.v1\"y\n" +
	"\x0fAddStoreRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12!\n" +
	"\frequested_by\x18\x04 \x01(\tR\vrequestedBy\">\n" +
	"\x10AddStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"!\n" +
	"\x0fGetStoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x10GetStoreResponse\x12+\n" +
	"\x05store\x18\x01 \x01(\v2\x10.stores.v1.StoreH\x00R\x05store\x88\x01\x01B\b\n" +
	"\x06_store\"\\\n" +
	"\x05Store\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x1d\n" +
	"\n" +
	"address_id\x18\x04 \x01(\tR\taddressId\"\x8c\x01\n" +
	"\x12UpdateStoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x1d\n" +
	"\n" +
	"address_id\x18\x04 \x01(\tR\taddressId\x12!\n" +
	"\frequested_by\x18\x05 \x01(\tR\vrequestedBy\"\\\n" +
	"\x13UpdateStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12+\n" +
	"\x05store\x18\x02 \x01(\v2\x10.stores.v1.StoreH\x00R\x05store\x88\x01\x01B\b\n" +
	"\x06_store\"G\n" +
	"\x12DeleteStoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\frequested_by\x18\x02 \x01(\tR\vrequestedBy\"%\n" +
	"\x13DeleteStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xd0\x01\n" +
	"\x12SearchStoreRequest\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12\x1f\n" +
	"\vaddress_str\x18\x04 \x01(\tR\n" +
	"addressStr\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bdistance\x18\a \x01(\rR\bdistance\"s\n" +
	"\x13SearchStoreResponse\x12+\n" +
	"\x06stores\x18\x01 \x03(\v2\x13.stores.v1.StoreGeoR\x06stores\x12'\n" +
	"\x03geo\x18\x02 \x01(\v2\x10.stores.v1.PointH\x00R\x03geo\x88\x01\x01B\x06\n" +
	"\x04_geo\"`\n" +
	"\bStoreGeo\x12&\n" +
	"\x05store\x18\x01 \x01(\v2\x10.stores.v1.StoreR\x05store\x12\x1f\n" +
	"\bdistance\x18\x02 \x01(\x02H\x00R\bdistance\x88\x01\x01B\v\n" +
	"\t_distance\"A\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude2\x86\x03\n" +
	"\x06Stores\x12E\n" +
	"\bAddStore\x12\x1a.stores.v1.AddStoreRequest\x1a\x1b.stores.v1.AddStoreResponse\"\x00\x12E\n" +
	"\bGetStore\x12\x1a.stores.v1.GetStoreRequest\x1a\x1b.stores.v1.GetStoreResponse\"\x00\x12N\n" +
	"\vUpdateStore\x12\x1d.stores.v1.UpdateStoreRequest\x1a\x1e.stores.v1.UpdateStoreResponse\"\x00\x12N\n" +
	"\vDeleteStore\x12\x1d.stores.v1.DeleteStoreRequest\x1a\x1e.stores.v1.DeleteStoreResponse\"\x00\x12N\n" +
	"\vSearchStore\x12\x1d.stores.v1.SearchStoreRequest\x1a\x1e.stores.v1.SearchStoreResponse\"\x00B1Z/github.com/comfforts/comff-stores/api/stores_v1b\x06proto3"

var (
	file_api_stores_v1_stores_proto_rawDescOnce sync.Once
	file_api_stores_v1_stores_proto_rawDescData []byte
)

func file_api_stores_v1_stores_proto_rawDescGZIP() []byte {
	file_api_stores_v1_stores_proto_rawDescOnce.Do(func() {
		file_api_stores_v1_stores_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stores_v1_stores_proto_rawDesc), len(file_api_stores_v1_stores_proto_rawDesc)))
	})
	return file_api_stores_v1_stores_proto_rawDescData
}

var file_api_stores_v1_stores_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_stores_v1_stores_proto_goTypes = []any{
	(*AddStoreRequest)(nil),     // 0: stores.v1.AddStoreRequest
	(*AddStoreResponse)(nil),    // 1: stores.v1.AddStoreResponse
	(*GetStoreRequest)(nil),     // 2: stores.v1.GetStoreRequest
	(*GetStoreResponse)(nil),    // 3: stores.v1.GetStoreResponse
	(*Store)(nil),               // 4: stores.v1.Store
	(*UpdateStoreRequest)(nil),  // 5: stores.v1.UpdateStoreRequest
	(*UpdateStoreResponse)(nil), // 6: stores.v1.UpdateStoreResponse
	(*DeleteStoreRequest)(nil),  // 7: stores.v1.DeleteStoreRequest
	(*DeleteStoreResponse)(nil), // 8: stores.v1.DeleteStoreResponse
	(*SearchStoreRequest)(nil),  // 9: stores.v1.SearchStoreRequest
	(*SearchStoreResponse)(nil), // 10: stores.v1.SearchStoreResponse
	(*StoreGeo)(nil),            // 11: stores.v1.StoreGeo
	(*Point)(nil),               // 12: stores.v1.Point
}
var file_api_stores_v1_stores_proto_depIdxs = []int32{
	4,  // 0: stores.v1.GetStoreResponse.store:type_name -> stores.v1.Store
	4,  // 1: stores.v1.UpdateStoreResponse.store:type_name -> stores.v1.Store
	11, // 2: stores.v1.SearchStoreResponse.stores:type_name -> stores.v1.StoreGeo
	12, // 3: stores.v1.SearchStoreResponse.geo:type_name -> stores.v1.Point
	4,  // 4: stores.v1.StoreGeo.store:type_name -> stores.v1.Store
	0,  // 5: stores.v1.Stores.AddStore:input_type -> stores.v1.AddStoreRequest
	2,  // 6: stores.v1.Stores.GetStore:input_type -> stores.v1.GetStoreRequest
	5,  // 7: stores.v1.Stores.UpdateStore:input_type -> stores.v1.UpdateStoreRequest
	7,  // 8: stores.v1.Stores.DeleteStore:input_type -> stores.v1.DeleteStoreRequest
	9,  // 9: stores.v1.Stores.SearchStore:input_type -> stores.v1.SearchStoreRequest
	1,  // 10: stores.v1.Stores.AddStore:output_type -> stores.v1.AddStoreResponse
	3,  // 11: stores.v1.Stores.GetStore:output_type -> stores.v1.GetStoreResponse
	6,  // 12: stores.v1.Stores.UpdateStore:output_type -> stores.v1.UpdateStoreResponse
	8,  // 13: stores.v1.Stores.DeleteStore:output_type -> stores.v1.DeleteStoreResponse
	10, // 14: stores.v1.Stores.SearchStore:output_type -> stores.v1.SearchStoreResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_stores_v1_stores_proto_init() }
func file_api_stores_v1_stores_proto_init() {
	if File_api_stores_v1_stores_proto != nil {
		return
	}
	file_api_stores_v1_stores_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_stores_v1_stores_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_stores_v1_stores_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_stores_v1_stores_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_stores_v1_stores_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stores_v1_stores_proto_rawDesc), len(file_api_stores_v1_stores_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stores_v1_stores_proto_goTypes,
		DependencyIndexes: file_api_stores_v1_stores_proto_depIdxs,
		MessageInfos:      file_api_stores_v1_stores_proto_msgTypes,
	}.Build()
	File_api_stores_v1_stores_proto = out.File
	file_api_stores_v1_stores_proto_goTypes = nil
	file_api_stores_v1_stores_proto_depIdxs = nil
}
